### ISSUE TITLE
"npm i" fails because of --debug argument to node-gyp-build

### ISSUE THREAD

**Issue by link2xt** [deltachat/deltachat-desktop-dev-env#11]
`/scripts/install.sh` runs `npm i` inside `deltachat-node`.

`npm i` runs `scripts/install.js`, which in turn execues `npm run node-gyp-build`.

@Simon-Laux You have modified `node-gyp-build` in https://github.com/deltachat/deltachat-node/commit/61978a3952d9f978ff5140e37122de72e2d99025 and added `--debug` option there.

When I run
```
$ npx node-gyp-build --debug "node scripts/rebuild-core.js" "node scripts/postinstall.js"
```
I get:
```
/bin/sh: 0: Illegal option --
```

Without `--debug` it works:
```
$ npx node-gyp-build "node scripts/rebuild-core.js" "node scripts/postinstall.js"
```

What is this `--debug` option and who outputs this unreadable error message?
```
/bin/sh: 0: Illegal option --
```

**Comment by Simon-Laux** [comment]
I saw it somewhere to enable debug symbols, so I included it. But it isn't necessary so I'll remove it again.

**Comment by Simon-Laux** [comment]
Where did you came across `/bin/sh: 0: Illegal option --`?

**Comment by link2xt** [comment]
It happens when I run node-gyp-build inside `./deltachat-node`:
```
$ npx node-gyp-build --debug "node scripts/rebuild-core.js" "node scripts/postinstall.js"
/bin/sh: 0: Illegal option --
$ npx node-gyp-build --debug
/bin/sh: 0: Illegal option --
$ npx node-gyp-build "node scripts/rebuild-core.js" "node scripts/postinstall.js"
<works correctly>
```

**Comment by Simon-Laux** [comment]
Ok I now removed that debug statement

**Comment by link2xt** [comment]
I would actually like to understand why does this error happen. @Simon-Laux  Do the commands I posted above work for you?

**Comment by Simon-Laux** [comment]
they all give out no error messages and just complete like any other successful command without output

**Comment by Simon-Laux** [comment]
also I'm using bash

**Comment by link2xt** [comment]
The error happens here for me:
https://github.com/prebuild/node-gyp-build/blob/81e3715fce06dd84c12b682a0be07264562b30f3/bin.js#L48

This line runs
```
/bin/sh -c --debug "node scripts/rebuild-core.js" "node scripts/postinstall.js"
```

On Debian `/bin/sh` points to `/bin/dash`. Here is what happens:
```
$ /bin/sh --debug
/bin/sh: 0: Illegal option --
$ dash --debug
dash: 0: Illegal option --
```

**Comment by link2xt** [comment]
Probably your `/bin/sh` points to something like `bash` which has `--debug` option.

**Comment by Simon-Laux** [comment]
Hmm.. anyways as I said I didn't knew what I was doing while adding it in the fist place.. so removing it solves this. Also It's not needed for lldb to work with breakpoints.
